// VER UNA LISTA DE CATEGORIAS

// VER LOS DETALLES DE UNA CATEGORIA

// REGISTRAR UNA NUEVA CATEGORIA 

// MODIFICAR UNA CATEGORIA

// ELIMINAR UNA CATEGORIA

// AGREGAR O QUITAR PRODUCTOS DE UNA CATEGORIA